require 'piece_pipe/pipeline'
require 'piece_pipe/step'

require 'piece_pipe/assembly_step'
require 'piece_pipe/collector'
require 'piece_pipe/debug_step'
require 'piece_pipe/hashed_aggregator'
require 'piece_pipe/map_step'
require 'piece_pipe/group_by_step'
require 'piece_pipe/method_assembly_step'
require 'piece_pipe/method_step'
require 'piece_pipe/tap_step'
require 'piece_pipe/version'
